version: '3'

services:
  app:
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD={DB_PASSWORD}
      - MYSQL_DATABASE={DB_NAME}
      - MYSQL_USERNAME={DB_USER}
      - MYSQL_PASSWORD={DB_PASSWORD}
    ports:
      - '3307:3306'
    volumes:
      - ./mysql-data:/var/lib/mysql